apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: cmpapi
  name: cmpapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cmpapi
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: golang
        name: cmpapi
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src/cmpapi
          name: cmpapi-claim0
      hostname: cmpapi
      restartPolicy: Always
      volumes:
      - name: cmpapi-claim0
        persistentVolumeClaim:
          claimName: cmpapi-claim0
status: {}
